import { Question } from './types';

export const PDF_CONTEXT = `
AI Safety Training Content Summary:

1. Identifying High-Risk Scenarios:
   - Automated systems like AI for job candidate selection via video analysis are considered high-risk.
   - Irrelevant visual factors (backgrounds, lighting) can bias outcomes.
   - Human oversight is crucial in these scenarios.

2. The 'Zero Trust' Principle:
   - Generative AI models can hallucinate or produce confident but incorrect information.
   - Users should never blindly trust AI outputs.
   - Always fact-check and verify information before use.
   - The user is the final decision maker.

3. Data Privacy and Security:
   - Information entered into public AI tools (ChatGPT, Claude, Gemini, etc.) is typically stored and may be used for model training.
   - There is a risk of data leakage.
   - Do not enter confidential, proprietary, or PII (Personally Identifiable Information) into these systems.

4. Transparency and the Law:
   - Under regulations like the AI Act, transparency is mandatory.
   - Content generated by AI that informs the public must be clearly labeled as artificially generated.
   - This ensures the audience is not misled about the source of the information.

5. Accountability:
   - AI lacks agency and true explainability.
   - The human operator ("human in the loop") retains full accountability for the AI's actions and mistakes.
   - Blaming the algorithm is not an acceptable defense for errors.
`;

export const QUIZ_QUESTIONS: Question[] = [
  {
    id: 1,
    title: "Identifying High-Risk Scenarios",
    text: "You are asked to use an AI platform that pre-selects job candidates by analyzing their application videos. According to the training, is this a viable and safe use of AI?",
    options: [
      { id: "A", text: "Yes, because AI is more objective than humans and saves time." },
      { id: "B", text: "No, because investigative reports show visual factors (like a bookshelf in the background) can bias the personality scores and lead to unfair decisions." },
      { id: "C", text: "Yes, as long as the AI has been trained on 'High-quality data.'" },
      { id: "D", text: "No, because AI is not allowed to process video files." },
    ],
    correctAnswerId: "B",
    explanation: "Investigative reports have shown that visual factors irrelevant to the job can bias AI personality scores, making this a high-risk and potentially unfair use case."
  },
  {
    id: 2,
    title: "The 'Zero Trust' Principle",
    text: "If an AI provides a very confident answer that includes 'lotto numbers' or a 'fact,' what should your default action be?",
    options: [
      { id: "A", text: "Trust it, because modern models like GPT-5 are meticulous and clear." },
      { id: "B", text: "Trust it only if it was generated using a 'System Prompt.'" },
      { id: "C", text: "Never trust AI blindly; always fact-check the output and take your own final decision." },
      { id: "D", text: "Assume it is correct unless the AI specifically mentions it might be 'hallucinating.'" },
    ],
    correctAnswerId: "C",
    explanation: "AI can hallucinate or be misaligned. The default state is often misalignment, so you must always fact-check and make the final decision."
  },
  {
    id: 3,
    title: "Data Privacy and Security",
    text: "What happens to the information you type into a web-based AI chatbot (like ChatGPT or Claude)?",
    options: [
      { id: "A", text: "It is deleted immediately after the session ends to protect your privacy." },
      { id: "B", text: "It is sent to and stored by the provider and may be used for model training or potentially exposed in a data leak." },
      { id: "C", text: "It is encrypted so that even the provider cannot see what you wrote." },
      { id: "D", text: "It is only stored if you click the 'Save' button." },
    ],
    correctAnswerId: "B",
    explanation: "Data sent to public AI providers is stored and often used for training. It should be treated as if it could be leaked."
  },
  {
    id: 4,
    title: "Transparency and the Law",
    text: "According to the AI Act guidelines mentioned in the presentation, what is required when you publish AI-generated text or video that informs the public?",
    options: [
      { id: "A", text: "You must pay a copyright fee to the AI provider." },
      { id: "B", text: "You must use a 'Privacy-Friendly AI' like a local model." },
      { id: "C", text: "You must label the content to show it was artificially generated." },
      { id: "D", text: "No labeling is required as long as the content is 100% accurate." },
    ],
    correctAnswerId: "C",
    explanation: "Transparency is a key requirement of the AI Act. Artificial content must be labeled as such to avoid misleading the public."
  },
  {
    id: 5,
    title: "Accountability for Mistakes",
    text: "In the event that an AI service (like a 'Vibe Coding' agent) makes a major error, such as deleting a production database, who is accountable?",
    options: [
      { id: "A", text: "The AI model, because it ignored the instructions." },
      { id: "B", text: "The company that built the AI tool." },
      { id: "C", text: "You are accountable for the decision, as AI lacks true explainability." },
      { id: "D", text: "The 'Master Agent' coordinating the sub-agents." },
    ],
    correctAnswerId: "C",
    explanation: "You are the human in the loop. Since AI lacks true explainability and agency, the responsibility for its actions and the final decision lies with you."
  },
];